CREATE TABLE If NOT EXISTS `bill` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file VARCHAR(255) NOT NULL,
  userId INT  NOT NULL,
  price float NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES `user`(id)

)ENGINE=INNODB;