
CREATE TABLE IF NOT EXISTS `clothes` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL , 
    gender VARCHAR(255) NOT NUll , 
    size VARCHAR(255) NOT NULL,
    price FLOAT NOT NULL,
    stock INT NOT NUll,
    image VARCHAR(255) NOT NULL 

)ENGINE=INNODB;